# GitHub Pages Configuration
title: "Alex Chen - AI/ML Engineer Portfolio"
description: "Professional portfolio showcasing 6+ years of AI/ML engineering experience"
author: "Alex Chen"
email: "alex.chen@email.com"
url: "https://yourusername.github.io"
baseurl: "/ai-ml-portfolio"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
twitter:
  username: alexchen
  card: summary_large_image

social:
  name: Alex Chen
  links:
    - https://github.com/alexchen
    - https://linkedin.com/in/alexchen
    - https://kaggle.com/alexchen

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - node_modules/
  - package.json
  - package-lock.json
